setup.py

In cases this fails, we can still use `providers.json` embedded in the library. There is a fallback for that on import. But the copy of `providers.json` to `share` on installation may fail and we don't want it to fail the installation itself.

REF: wrap providers.json install in try/except

---

.github/workflows/release_to_pypi.yml

Adding GHA that automatically releases `xyservices` to GitHub and PyPI. It is the same one we use in geopandas and dask-geopandas using my PyPI token.
It will create a release from any tag starting with 2 (e.g. 2021.08) following #26.

GHA: add release action

---

.github/workflows/compress_providers.yaml

Automatically runs `make compress` and commits the result to a PR labelled `community_contribution`.

GHA: commit compressed providers to PRs

---

tests/test_providers.py

It seems that CI may occasionally fail while fetching data from QMS (https://github.com/geopandas/xyzservices/runs/3266305686). Marking with `xfail` to ensure it does not cause CI failure.

CI: xfail qms tests

---

tests/test_providers.py

follow-up on #72 to ensure the test fails if any other error than `URLError` is raised.

CI: xfail qms only on URLError

---

tests/test_providers.py
xyzservices/lib.py

Closes #62
You can now get a URL with `{s}` placeholder intact if that is required.
I have also moved definition of providers in tests to fixtures.

ENH: add `fill_subdomain` keyword to `build_url`

---

ci/latest.yaml
doc/source/introduction.ipynb
provider_sources/_compress_providers.py
tests/test_lib.py
tests/test_providers.py
xyzservices/data/providers.json

Splitting test suite into 2 files and adding tests that check all providers that do not require any API key.
I will also add a machinery marking broken sources coming from leaflet-providers and removing them from the compressed json. Just want to run CI before that to show how it behaves with broken tiles.
Some (Stadia) do not require API key according to our metadata but the domain needs to be whitelisted to make them work. Those give 403 error and are xfailed.

TST: test openly accessible tiles and mark broken with `status="broken"` flag

---

doc/source/index.md
doc/source/introduction.ipynb
doc/source/registration.md

Using the [`leaflet-providers` project description](https://github.com/leaflet-extras/leaflet-providers/blob/master/README.md) of providers requiring API token/registration + minor edits of the docs.

DOC: document registrations, add disclaimers

---

tests/test_providers.py

CI sometimes fails on 502 (randomly) - https://github.com/geopandas/xyzservices/runs/3275162345. xfailing that.

TST: xfail error 502

---

CHANGELOG.md
provider_sources/_compress_providers.py
provider_sources/xyzservices-providers.json
xyzservices/data/providers.json

I have added some providers which were missing here and present in [ipyleaflet](https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/basemaps.py)
Also while adding provider found an issue in `provider_sources/_compress_providers.py`
If Group is already present and if we add new basemaps to the same group then it is overriding the dictionary due to line https://github.com/geopandas/xyzservices/blob/1f6ac89f4aaf7ab04ab40f5c659c32f100b8c3c6/provider_sources/_compress_providers.py#L52
example:
`OpenStreetMap` group is already present, If I add a new entry in this group then as per existing code it will replace the value and will keep only the new value, it is not updating the dictionary.
Please correct me if I am wrong.
I have also created PR # …

Ipyleaflet providers and fix for compress providers

---

.github/workflows/tests.yaml
tests/test_providers.py

I am trying to figure out a way of testing providers that require API tokens. It seems to be doable:
1. register and get API token
2. store it as a repository secret
3. load it in `tests.yaml`
4. load it via `os.environ` in tests
Note that secrets are loaded as empty strings if the PR is coming from a fork. We xfail in that case. I am going to merge this to trigger proper test and open a new PR adding other services as a branch of upstream.

TST: test providers requiring API token

---

.github/workflows/tests.yaml
doc/source/registration.md
tests/test_providers.py

With this PR, all our providers are tested with two exceptions: `HERE` and `AzureMaps`.
`HERE` contains legacy authentication requiring `app_id` and `app_code` which is not possible to obtain anymore. It has been replaced by `HEREv3` with `apiKey`. That one is tested.
`AzureMaps` have a free tier limited to 5000 requests in total, not per month. If I created a token on my account as I did with other services, it would eventually overflow and charged me. Hence not tested at the moment.

TST: test more providers requiring API keys

---

.github/workflows/tests.yaml
pytest.ini
tests/test_providers.py

We don't need to check if the tiles exist in all environments. And due to the limits of free tiers we use in CI, we should try to minimize the number of requests.
Marking tests that fetch tiles from a remote server and running those only in ubuntu env, so it is done once, not 3x.

CI: fetch tiles only under ubuntu

---

CHANGELOG.md
doc/source/api.rst
tests/test_lib.py
xyzservices/lib.py

`query_name()` returns the TileProvider object based on the lowercase string stripped of additional characters. E.g.:
All these queries return the same ``CartoDB.Positron`` TileProvider:
```py
>>> xyz.query_name("CartoDB Positron")
>>> xyz.query_name("cartodbpositron")
>>> xyz.query_name("cartodb-positron")
>>> xyz.query_name("carto db/positron")
>>> xyz.query_name("CARTO_DB_POSITRON")
>>> xyz.query_name("CartoDB.Positron")
```
It makes easier implementing relaxed string input in downstream, e.g. https://github.com/geopandas/geopandas/pull/1953#discussion_r69749762
An implementation in GeoPandas then can be something along this:
```py
def explore(... tiles=None...):
try:
tiles = xyz.query_name(tiles)
except ValueError:
pass
```
This either replaces the string with TileProvider object or …

ENH: implement Bunch.query_name()

---

setup.py

The current setup packages the tests directory as a module. B/c many Python libraries make that mistake it causes clobber errors downstream. This PR removes this behavior but if the authors want to ship the tests with the library the "right" thing to do is to move it inside the module folder.

do not package a tests module

---

doc/source/contributing.md

adding a note on the format of `bounds`

DOC: document bounds usage in JSON

---

provider_sources/xyzservices-providers.json
xyzservices/data/providers.json
xyzservices/tests/test_providers.py

Adding polar projected Arctic and Antarctic Basemaps provided by Esri
* [Map Viewer for Arctic Ocean Basemap](https://www.arcgis.com/apps/mapviewer/index.html?webmap=c7381cb155a043a2bba2b84566677262)
* [Map Viewer for Antarctic Ocean Basemap](https://www.arcgis.com/apps/mapviewer/index.html?webmap=d13b9d10219e4429974e48368b64e41f)
xyzservices-providers.json has been updated with the new sources and the compressed file has been made

Add Esri Arctic and Antarctic Basemaps

---

provider_sources/xyzservices-providers.json
xyzservices/data/providers.json

- Adding polar projected Arctic Ocean Imagery provided by Esri
[Map Viewer for Arctic Ocean Imagery](https://www.arcgis.com/apps/mapviewer/index.html?webmap=7ec08e5438304dbfa1e26181503e6fa8)
- Adding polar projected Antarctic Imagery provided by Esri
[Map Viewer for Antarctic Imagery](https://www.arcgis.com/apps/mapviewer/index.html?webmap=6553466517dd4d5e8b0c518b8d6b64cb)
- Adding NASA ASTER GDEM
[EOSDIS WorldView with NASA ASTER GDEM](https://worldview.earthdata.nasa.gov/?l=ASTER_GDEM_Greyscale_Shaded_Relief)
xyzservices-providers.json has been updated with the new sources and the compressed file has been made

Add Esri Arctic Imagery and NASA ASTER GDEM

---

doc/source/conf.py

This fixes https://github.com/geopandas/xyzservices/issues/117
It allows build documentation witout have module installd and
it adds path to `xyzservices` code to the `sys.path`
That kind of adjustment is suggested to use in ossifial sphinx
example conf.py file
https://www.sphinx-doc.org/en/master/usage/configuration.html#example-of-configuration-file
Signed-off-by: Tomasz Kłoczko <kloczek@github.com>

DOC: Fix building documentation out of source tree #117

---

.github/workflows/release_to_pypi.yml

Resolving this annotation from GHA:
> [Build and publish xyzservices to PyPI: # >> PyPA publish to PyPI GHA: UNSUPPORTED GITHUB ACTION VERSION <<#L1](https://github.com/geopandas/xyzservices/commit/e6315d8026569fa7626a265ae9d89642d4a75aae#annotation_4652189477)
You are using "pypa/gh-action-pypi-publish@master". The "master" branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use "pypa/gh-action-pypi-publish@release/v1". If you feel adventurous, you may opt to use use "pypa/gh-action-pypi-publish@unstable/v1" instead. A more general recommendation is to pin to exact tags or commit shas.

GHA: update PyPI release action

---

xyzservices/tests/test_providers.py

Stadia changed their conditions and we no longer can download PNGs as we do in our CI. Skipping.

TST: skip Stadia tiles in tests

---

provider_sources/xyzservices-providers.json
xyzservices/data/providers.json

We have stamen tiles under Stadia now but since the original tiles still work (until end of Oct), keep them included and remove once they're off.

PRO: include stamen directly until october

---

provider_sources/xyzservices-providers.json
xyzservices/data/providers.json

The API endpoint for `BlueMarble3031` and `BlueMarble3413` isn't correct in the json file. Thus, the endpoint is refactored as per guideline [here](https://gibs.earthdata.nasa.gov/wmts/epsg3031/best/1.0.0/WMTSCapabilities.xml) and [here](https://gibs.earthdata.nasa.gov/wmts/epsg3413/best/1.0.0/WMTSCapabilities.xml).

fixed url endpoint for BlueMarble3031 and BlueMarble3413

---

provider_sources/_compress_providers.py
provider_sources/leaflet-providers-parsed.json
xyzservices/data/providers.json
xyzservices/tests/test_lib.py

#165 
This PR migrates the ign WMTS services to the new service: `https://data.geopf.fr/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities`
The new services don't have a categorizing key, like agriculture...
So I removed the apiKey as well as its test.
Edit
The test_callable is actually needed.

Migrate ign wmts services

---

.pre-commit-config.yaml
provider_sources/_parse_leaflet_providers.py
xyzservices/lib.py
xyzservices/tests/test_lib.py

This PR does two things:
- pre-commit: Update to latest ruff, set autoupdate schedule to monthly
- Apply latest ruff and ruff-format
I can highly recommend enabling and using https://pre-commit.ci/, it will not only run pre-commit very fast, it will also periodically check if there are any updates available to the pre-commit configuration.

Update and apply latest ruff, update pre-commit
