- .github/workflows/update_providers.yaml
I did this on `geopandas/xyzservices`, whoops, but hopefully does the job.
> Update GA, fix #39

- .github/workflows/tests.yaml
- .pre-commit-config.yaml
- provider_sources/_compress_providers.py
- provider_sources/_parse_leaflet_providers.py
- setup.cfg
- xyzservices/__init__.py
- xyzservices/_version.py
- xyzservices/lib.py
- xyzservices/providers.py
Reformat code using black, isort, and flake8, add pre-commit hook and a style check to CI.
> STY/CI: linting

- .github/PULL_REQUEST_TEMPLATE/community_contribution.md
- CONTRIBUTING.md
- doc/source/contributing.md
- doc/source/index.md
> DOC: contributing guide

- doc/source/api.rst
- tests/test_providers.py
- xyzservices/lib.py
Fixes https://github.com/geopandas/xyzservices/issues/65
> ENH: Add TileProvider.from_qms()

- doc/source/api.rst
- tests/test_providers.py
- xyzservices/_version.py
- xyzservices/lib.py
Closes #42
`Bunch.filter` returns subset based on set conditions.
> ENH: add `Bunch.filter` method to filter specific providers

- provider_sources/xyzservices-providers.json
- xyzservices/data/providers.json
> fix Strava links

- tests/test_providers.py
Gaode tiles have a tendency to hang sometimes. This should resolve it.
> TST: add timeout

- provider_sources/_compress_providers.py
- xyzservices/data/providers.json
`nlmaps.luchtfoto` and `NASAGIBS.ModisTerraSnowCover` have been fixed in upstream
> PRO: remove broken markers

- provider_sources/xyzservices-providers.json
- xyzservices/data/providers.json
> Add Blue Marble base maps

- provider_sources/xyzservices-providers.json
- xyzservices/data/providers.json
> add additional MapTiler tiles

- provider_sources/xyzservices-providers.json
- xyzservices/data/providers.json
Testing providers requiring authentication is disabled for PRs, so need to merge to see if it works.
> fix maptiler

- provider_sources/xyzservices-providers.json
needs to be merged to run CI on this one (requires a token)
> fix Maptiler.Winter extension

- doc/source/_static/styles.css
- doc/source/gallery.rst
Makes the iframe take the correct width.
> A tiny bit of styling

- .gitignore
- doc/source/_static/generate_gallery.js
- doc/source/gallery.rst
Inlining the gallery in the documentation instead of relying on an iframe makes the scrolling behavior a bit nicer.
> Remove iframe

- .github/workflows/tests.yaml
- .pre-commit-config.yaml
- xyzservices/providers.py
xref https://github.com/geopandas/geodatasets/pull/8
> REF: use pkgutil in fallback read of JSON

- provider_sources/_compress_providers.py
This will need `make update-leaflet` and `make compress` but I don't have deps locally and will let CI run it.
> Label Orthoimagery_Orthophotos_1980_1995 as broken

- .github/workflows/update_providers.yaml
- ci/update_providers.yaml
trying to debug https://github.com/geopandas/xyzservices/actions/runs/5732972770
> CI: pin selenium

- .github/workflows/tests.yaml
- .pre-commit-config.yaml
use setup-micromamba and ruff-format
> CI: update CI and pre-commit

- provider_sources/xyzservices-providers.json
- xyzservices/data/providers.json
add NASA GIBS ice velocity basemaps for Greenland and Antarctica
> add NASA GIBS blue marble with bathymetry

- provider_sources/xyzservices-providers.json
- xyzservices/data/providers.json
Adding 2 base maps:
* [NASA's BlueMarble](https://worldview.earthdata.nasa.gov/?l=Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,BlueMarble_NextGeneration,MODIS_Terra_CorrectedReflectance_TrueColor&lg=false&t=2024-06-24-T00%3A54%3A11Z)
* [ESRI's world imagery](https://www.arcgis.com/apps/mapviewer/index.html?layers=10df2279f9684e4a9f6a7f08febac2a9)
> Adding back NASA's BlueMarble

- README.md
Add a clickable PyPI version badge, to conveniently show the latest version available on PyPI.
[![PyPi](https://img.shields.io/pypi/v/xyzservices.svg)](https://pypi.python.org/pypi/xyzservices)
> README.md: Add PyPI version badge.

- provider_sources/xyzservices-providers.json
- xyzservices/data/providers.json
Added the [UN Clear Map](https://www.un.org/geospatial/mapsgeo/webservices)
> feat: add UN clear map
